// Gerçekçi Demo ve Yedek Veriler (Embay Yapı & Şahin Manitou)
// Demo modunda veya veritabanı boş olduğunda arayüzün canlı, dolu ve test edilebilir kalmasını sağlar.

export function isDemoMode(): boolean {
  return typeof window !== 'undefined' && sessionStorage.getItem('embay_demo_mode') === 'true';
}

export const DEMO_VIDEOS = [
  {
    id: 'demo-vid-1',
    kind: 'video' as const,
    title: '150 Günde Anahtar Teslim Villa İnşaatı — Temel ve Kaba İlerleme',
    url: '/brand/video/embay-150-gunde-villa.mp4',
    original_url: '/brand/video/embay-150-gunde-villa.mp4',
    cover_url: '/brand/video/embay-150-gunde-villa-kapak.jpg',
    mime: 'video/mp4',
    size_bytes: 18450000,
    duration_sec: 24,
    width: 1080,
    height: 1920,
    targets: ['ig_reel', 'yt_short', 'fb_post'],
    caption: 'Güngören & Çatalca projelerimizde 150 günde anahtar teslim konut taahhüdü. Deprem yönetmeliğine tam uyumlu radye temel, C35 beton ve nervürlü demir kalıp imalatı. ☎ 0531 436 29 04',
    hashtags: ['#embayyapı', '#villainşaatı', '#kentseldönüşüm', '#temelkalıp', '#çatalca', '#istanbul'],
    edit: { trim_start: 0, trim_end: 24, muted: false },
    notes: 'Kurgulu ana tanıtım reels videosu',
    status: 'pool' as const,
    draft_ids: [],
    queued_at: null,
    created_at: new Date(Date.now() - 3600_000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-vid-2',
    kind: 'video' as const,
    title: 'Şahin Manitou MT-X 1840 Sahada — 18 Metre Yüksek İrtifa Yükleme',
    url: '/public/brand/video/embay-tanitim-01.mp4',
    original_url: '/public/brand/video/embay-tanitim-01.mp4',
    cover_url: '/reels/82d879bd-1f6c-4cb4-844f-8667ac972bfb.jpg',
    mime: 'video/mp4',
    size_bytes: 14200000,
    duration_sec: 18,
    width: 1080,
    height: 1920,
    targets: ['ig_reel', 'yt_short'],
    caption: 'İstanbul Avrupa ve Anadolu yakası şantiyelerine uzman operatörlü 14m ve 18m Manitou teleskopik yükleyici kiralama. Sepet, çatal ve bom ataşmanlarıyla hızlı sevk. ☎ 0531 436 29 04',
    hashtags: ['#şahinmanitou', '#manitoukiralama', '#teleskopikyükleyici', '#şantiyelojistik', '#inşaat'],
    edit: { trim_start: 0, trim_end: 18, muted: false },
    notes: 'Manitou saha operasyonu',
    status: 'pool' as const,
    draft_ids: [],
    queued_at: null,
    created_at: new Date(Date.now() - 3600_000 * 12).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-vid-3',
    kind: 'video' as const,
    title: 'Güngören Tozkoparan Kentsel Dönüşüm Şantiyesi — Beton Dökümü',
    url: '/reels/25457fa7-5b80-41fd-b9be-24054d0b11a3.mp4',
    original_url: '/reels/25457fa7-5b80-41fd-b9be-24054d0b11a3.mp4',
    cover_url: '/reels/25457fa7-5b80-41fd-b9be-24054d0b11a3.jpg',
    mime: 'video/mp4',
    size_bytes: 9800000,
    duration_sec: 15,
    width: 1080,
    height: 1920,
    targets: ['ig_reel', 'fb_post'],
    caption: 'Güngören bölgesinde deprem riskli binaları modern ve güvenli yaşam alanlarına dönüştürüyoruz. Kat malikleri ile şeffaf sözleşme ve zamanında teslim garantisi.',
    hashtags: ['#kentseldönüşüm', '#güngören', '#tozkoparan', '#depremgüvenliği', '#embayyapı'],
    edit: { trim_start: 0, trim_end: 15, muted: false },
    notes: 'Tozkoparan saha çekimi',
    status: 'pool' as const,
    draft_ids: [],
    queued_at: null,
    created_at: new Date(Date.now() - 86400_000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-vid-4',
    kind: 'video' as const,
    title: 'Kalıp & Demir İmalatı — Kolon-Kiriş Donatı Kontrolü',
    url: '/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.mp4',
    original_url: '/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.mp4',
    cover_url: '/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.jpg',
    mime: 'video/mp4',
    size_bytes: 8400000,
    duration_sec: 12,
    width: 1080,
    height: 1920,
    targets: ['ig_reel', 'yt_short'],
    caption: 'Götürü ve taşeron kaba inşaat işlerinde usta kalıp ve demir ekiplerimiz sahada. Projeye ve statik hesaplara milimetrik uygunluk.',
    hashtags: ['#kalıpdemir', '#kabainşaat', '#müteahhitlik', '#şantiye', '#embayyapı'],
    edit: { trim_start: 0, trim_end: 12, muted: false },
    notes: 'Kalıp demir detay videosu',
    status: 'pool' as const,
    draft_ids: [],
    queued_at: null,
    created_at: new Date(Date.now() - 86400_000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_AUDIO_TRACKS = [
  { id: 'track-reels', name: 'Şantiye & Endüstriyel Dinamik Bas', src: '/scripts/reels/music.m4a', duration: '0:32', mood: 'Dinamik / Şantiye' },
  { id: 'track-urban', name: 'Modern Kentsel Dönüşüm Beat', src: '/scripts/reels/music.m4a', duration: '0:28', mood: 'Kurumsal / İlham Verici' },
  { id: 'track-tempo', name: 'Hızlı İlerleme & Reels Ritim', src: '/scripts/reels/music.m4a', duration: '0:25', mood: 'Hızlı / Enerjik' },
];

export const DEMO_REALISTIC_DRAFTS = [
  {
    id: 'demo-draft-1',
    title: 'Genel İnşaat Reels: 150 Günde Temelden Çatıya Villa İnşaatı',
    body: 'Çatalca ve Silivri hattında müstakil villa projelerimiz hızla yükseliyor. Temelden anahtar teslime kadar statik ve mimari taahhüt. ☎ 0531 436 29 04',
    caption: 'Çatalca ve Silivri hattında müstakil villa projelerimiz hızla yükseliyor. Temelden anahtar teslime kadar statik ve mimari taahhüt. Detaylı keşif için bize ulaşın: 0531 436 29 04',
    headline: '150 GÜNDE ANAHTAR TESLİM VİLLA',
    hashtags: ['#inşaat', '#villayapımı', '#çatalca', '#müteahhitlik', '#embayyapı'],
    cta: 'Hemen Keşif İsteyin',
    primary_platform: 'instagram',
    platform_targets: ['instagram', 'youtube'],
    networks: ['instagram', 'youtube'],
    format: 'instagram_reel',
    status: 'onay_bekliyor',
    workflow_status: 'pending_approval',
    scheduled_at: new Date(Date.now() + 3600_000 * 2).toISOString(),
    media_urls: ['/brand/video/embay-150-gunde-villa-kapak.jpg'],
    video_url: '/brand/video/embay-150-gunde-villa.mp4',
    brand: 'Embay Yapı',
    created_at: new Date().toISOString(),
    approval_request_id: 'appr-1',
  },
  {
    id: 'demo-draft-2',
    title: 'Manitou Kiralama: 18m Operatörlü Teleskopik Yükleyici',
    body: 'Güngören, Hadımköy, Çorlu ve İkitelli şantiyelerinde aynı gün teslim operatörlü Manitou MT-X 1840. Malzeme paleti ve cam montajı sepeti dahil.',
    caption: 'İstanbul geneli şantiyelerinize aynı gün sevk! 18 Metre erişim, 4 ton kaldırma kapasitesi, sertifikalı operatör güvencesi. Teklif hattı: 0531 436 29 04',
    headline: 'OPERATÖRLÜ MANİTOU KİRALAMA',
    hashtags: ['#manitoukiralama', '#şahinmanitou', '#inşaatmakinesi', '#şantiye'],
    cta: 'Teklif Al: 0531 436 29 04',
    primary_platform: 'instagram',
    platform_targets: ['instagram', 'facebook'],
    networks: ['instagram', 'facebook'],
    format: 'instagram_post',
    status: 'zamanlandi',
    workflow_status: 'scheduled',
    scheduled_at: new Date(Date.now() + 3600_000 * 6).toISOString(),
    media_urls: ['/reels/82d879bd-1f6c-4cb4-844f-8667ac972bfb.jpg'],
    video_url: null,
    brand: 'Şahin Manitou',
    created_at: new Date().toISOString(),
    approval_request_id: 'appr-2',
  },
  {
    id: 'demo-draft-3',
    title: 'Kentsel Dönüşüm Gönderisi: Depreme Dayanıklı Temel İmalatı',
    body: 'Güngören Tozkoparan’da yerinde dönüşüm projelerimizde radye temel ve C35 hazır beton kalitesiyle geleceğinizi güvenceye alıyoruz.',
    caption: 'Güngören Tozkoparan’da yerinde dönüşüm projelerimizde radye temel ve C35 hazır beton kalitesiyle geleceğinizi güvenceye alıyoruz. Bina analizi ve kat malikleri toplantısı için arayabilirsiniz.',
    headline: 'GÜNGÖREN KENTSEL DÖNÜŞÜM',
    hashtags: ['#kentseldönüşüm', '#güngören', '#depremyönetmeliği', '#embayyapı'],
    cta: 'Ücretsiz Danışmanlık',
    primary_platform: 'linkedin',
    platform_targets: ['linkedin', 'facebook'],
    networks: ['linkedin', 'facebook'],
    format: 'linkedin_post',
    status: 'onaylandi',
    workflow_status: 'approved',
    scheduled_at: new Date(Date.now() + 86400_000).toISOString(),
    media_urls: ['/brand/embay-kapak.jpg'],
    video_url: null,
    brand: 'Embay Yapı',
    created_at: new Date().toISOString(),
    approval_request_id: 'appr-3',
  },
  {
    id: 'demo-draft-4',
    title: 'Şantiye Hikayesi: Kolon Demiri Bağlama & Statik Kontrol',
    body: 'Şantiyede bugünün mesaisi: 4. kat döşeme ve perde demirleri bağlandı, yapı denetim onayı tamam. Yarın sabah 07:00 beton dökümü.',
    caption: 'Perde ve kolon donatı imalatı tamamlandı. Embay Yapı kalitesi her aşamada şeffaf.',
    headline: 'ŞANTİYEDE BUGÜN',
    hashtags: ['#şantiye', '#embayyapı', '#hikaye'],
    cta: '0531 436 29 04',
    primary_platform: 'instagram',
    platform_targets: ['instagram'],
    networks: ['instagram'],
    format: 'instagram_story',
    status: 'taslak',
    workflow_status: 'draft',
    scheduled_at: new Date(Date.now() + 86400_000 * 2).toISOString(),
    media_urls: ['/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.jpg'],
    video_url: null,
    brand: 'Embay Yapı',
    created_at: new Date().toISOString(),
    approval_request_id: null,
  },
];

export const DEMO_ENGAGEMENT_LEADS = [
  {
    id: 'eng-1',
    author: 'Karadeniz İnşaat Taahhüt',
    handle: 'karadeniz_yapi_ist',
    platform: 'instagram',
    url: 'https://www.instagram.com/p/C7X123456/',
    summary: 'Hadımköy Sanayi Sitesi 2. Kısım için götürü kaba inşaat kalıp demir taşeronu aranıyor (3 katlı fabrika yapısı).',
    suggested_comment: 'Merhaba, Hadımköy sanayi şantiyelerine kendi kalıp-demir ekiplerimiz ve Manitou yükleyicilerimizle anahtar teslim taahhüt veriyoruz. Detayları görüşmek isteriz ☎ 0531 436 29 04',
    category: 'Götürü Kaba İnşaat / Taşeron Arayışı',
    phone: '0532 410 XX XX',
    likes: 42,
    comments: 8,
    is_liked: false,
    is_commented: false,
  },
  {
    id: 'eng-2',
    author: 'Avrupa Prefabrik & Çelik',
    handle: 'avrupa_celik_yapi',
    platform: 'instagram',
    url: 'https://www.instagram.com/p/C8Y987654/',
    summary: 'Çorlu Çerkezköy organize sanayi bölgesinde çelik çatı ve panel montajı için 18 metre sepetli Manitou telehandler aranıyor.',
    suggested_comment: 'Merhaba, Şahin Manitou olarak 18m MT-X 1840 makinelerimiz ve uzman operatörlerimizle Çorlu ve Çerkezköy şantiyelerine günlük/haftalık sevk yapıyoruz. ☎ 0531 436 29 04',
    category: 'Manitou / Telehandler Arayışı',
    phone: '0533 620 XX XX',
    likes: 85,
    comments: 14,
    is_liked: false,
    is_commented: false,
  },
  {
    id: 'eng-3',
    author: 'Tozkoparan Konut Sakinleri Platformu',
    handle: 'tozkoparan_donusum',
    platform: 'instagram',
    url: 'https://www.instagram.com/p/C9Z112233/',
    summary: 'Güngören Tozkoparan’da 18 daireli binamız için kentsel dönüşüm müteahhidi arıyoruz. Güvenilir ve yerel firma teklifleri bekleniyor.',
    suggested_comment: 'Embay Yapı olarak Güngören Tozkoparan merkezli çalışıyor, deprem yönetmeliğine uygun projelendirme ve garantili teslim yapıyoruz. Ücretsiz ön keşif için Samet Bey ile görüşebilirsiniz: 0531 436 29 04',
    category: 'Kentsel Dönüşüm / Müteahhitlik Talebi',
    phone: '0530 115 XX XX',
    likes: 129,
    comments: 31,
    is_liked: false,
    is_commented: false,
  },
];
