// Gerçekçi Demo ve Yedek Veriler (Embay Yapı & Şahin Manitou)
// Demo modunda veya veritabanı boş olduğunda arayüzün canlı, dolu ve test edilebilir kalmasını sağlar.

export function isDemoMode(): boolean {
  return typeof window !== 'undefined' && sessionStorage.getItem('embay_demo_mode') === 'true';
}

export const DEMO_VIDEOS = [
  {
    id: 'demo-vid-1',
    kind: 'video' as const,
    source: 'montage' as const,
    is_edited: true,
    title: '[KURGULU REELS] 150 Günde Anahtar Teslim Villa — Müzikli & Kancalı Edit',
    url: '/brand/video/embay-150-gunde-villa.mp4',
    original_url: '/brand/video/embay-150-gunde-villa.mp4',
    cover_url: '/brand/video/embay-150-gunde-villa-kapak.jpg',
    mime: 'video/mp4',
    size_bytes: 18450000,
    duration_sec: 24,
    width: 1080,
    height: 1920,
    targets: ['ig_reel', 'yt_short', 'fb_post'],
    caption: 'Güngören & Çatalca projelerimizde 150 günde anahtar teslim konut taahhüdü. Deprem yönetmeliğine tam uyumlu radye temel, C35 beton ve nervürlü demir kalıp imalatı. ☎ 0531 436 29 04',
    hashtags: ['#embayyapı', '#villainşaatı', '#kentseldönüşüm', '#temelkalıp', '#çatalca', '#istanbul'],
    edit: { trim_start: 0, trim_end: 24, muted: false, montage: { template: 'villa', hook: '150 GÜNDE TESLİM EDİYORUZ' } },
    hook_text: '150 GÜNDE ANAHTAR TESLİM VİLLA TAAHHÜDÜ',
    music_track: 'Şantiye & Endüstriyel Dinamik Bas',
    music_url: '/audio/music.m4a',
    notes: 'Kurgulanmış müzikli dikey Reels videosu',
    status: 'pool' as const,
    draft_ids: ['demo-draft-1'],
    queued_at: null,
    created_at: new Date(Date.now() - 3600_000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-vid-2',
    kind: 'video' as const,
    source: 'montage' as const,
    is_edited: true,
    title: '[KURGULU REELS] Şahin Manitou MT-X 1840 Sahada — 18 Metre Yüksek İrtifa Yükleme',
    url: '/brand/video/embay-tanitim-01.mp4',
    original_url: '/brand/video/embay-tanitim-01.mp4',
    cover_url: '/reels/82d879bd-1f6c-4cb4-844f-8667ac972bfb.jpg',
    mime: 'video/mp4',
    size_bytes: 14200000,
    duration_sec: 18,
    width: 1080,
    height: 1920,
    targets: ['ig_reel', 'yt_short'],
    caption: 'İstanbul Avrupa ve Anadolu yakası şantiyelerine uzman operatörlü 14m ve 18m Manitou teleskopik yükleyici kiralama. Sepet, çatal ve bom ataşmanlarıyla hızlı sevk. ☎ 0531 436 29 04',
    hashtags: ['#şahinmanitou', '#manitoukiralama', '#teleskopikyükleyici', '#şantiyelojistik', '#inşaat'],
    edit: { trim_start: 0, trim_end: 18, muted: false, montage: { template: 'manitou', hook: '18 METREDE GÜVENLİ YÜKLEME' } },
    hook_text: 'OPERATÖRLÜ 18M MANİTOU KİRALAMA',
    music_track: 'Hızlı İlerleme & Reels Ritim',
    music_url: '/audio/music.m4a',
    notes: 'Manitou saha operasyonu müzikli kurgu',
    status: 'pool' as const,
    draft_ids: ['demo-draft-2'],
    queued_at: null,
    created_at: new Date(Date.now() - 3600_000 * 12).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-vid-3',
    kind: 'video' as const,
    source: 'montage' as const,
    is_edited: true,
    title: '[KURGULU REELS] Güngören Tozkoparan Kentsel Dönüşüm — Beton Dökümü & Donatı',
    url: '/reels/25457fa7-5b80-41fd-b9be-24054d0b11a3.mp4',
    original_url: '/reels/25457fa7-5b80-41fd-b9be-24054d0b11a3.mp4',
    cover_url: '/reels/25457fa7-5b80-41fd-b9be-24054d0b11a3.jpg',
    mime: 'video/mp4',
    size_bytes: 9800000,
    duration_sec: 15,
    width: 1080,
    height: 1920,
    targets: ['ig_reel', 'fb_post'],
    caption: 'Güngören bölgesinde deprem riskli binaları modern ve güvenli yaşam alanlarına dönüştürüyoruz. Kat malikleri ile şeffaf sözleşme ve zamanında teslim garantisi.',
    hashtags: ['#kentseldönüşüm', '#güngören', '#tozkoparan', '#depremgüvenliği', '#embayyapı'],
    edit: { trim_start: 0, trim_end: 15, muted: false, montage: { template: 'asamalar', hook: 'DEPREME DAYANIKLI STATİK TEMEL' } },
    hook_text: 'TOZKOPARAN YERİNDE KENTSEL DÖNÜŞÜM',
    music_track: 'Modern Kentsel Dönüşüm Beat',
    music_url: '/audio/music.m4a',
    notes: 'Tozkoparan saha çekimi kurgulu edit',
    status: 'pool' as const,
    draft_ids: ['demo-draft-3'],
    queued_at: null,
    created_at: new Date(Date.now() - 86400_000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-vid-4',
    kind: 'video' as const,
    source: 'montage' as const,
    is_edited: true,
    title: '[KURGULU REELS] Kalıp & Demir İmalatı — Kolon-Kiriş Donatı Kontrolü',
    url: '/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.mp4',
    original_url: '/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.mp4',
    cover_url: '/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.jpg',
    mime: 'video/mp4',
    size_bytes: 8400000,
    duration_sec: 12,
    width: 1080,
    height: 1920,
    targets: ['ig_reel', 'yt_short'],
    caption: 'Götürü ve taşeron kaba inşaat işlerinde usta kalıp ve demir ekiplerimiz sahada. Projeye ve statik hesaplara milimetrik uygunluk.',
    hashtags: ['#kalıpdemir', '#kabainşaat', '#müteahhitlik', '#şantiye', '#embayyapı'],
    edit: { trim_start: 0, trim_end: 12, muted: false, montage: { template: 'santiye', hook: 'USTA EKİPLERLE KALIP & DEMİR' } },
    hook_text: 'ŞANTİYEDE STATİK DONATI KONTROLÜ',
    music_track: 'Şantiye & Endüstriyel Dinamik Bas',
    music_url: '/audio/music.m4a',
    notes: 'Kalıp demir detay kurgusu',
    status: 'pool' as const,
    draft_ids: ['demo-draft-4'],
    queued_at: null,
    created_at: new Date(Date.now() - 86400_000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-vid-5',
    kind: 'video' as const,
    source: 'upload' as const,
    is_edited: false,
    title: 'Ham Çekim: Şantiye Perde Beton Donatı İncelemesi',
    url: '/reels/818171bd-dd06-4fb3-bfd2-42c5040a3381.mp4',
    original_url: '/reels/818171bd-dd06-4fb3-bfd2-42c5040a3381.mp4',
    cover_url: '/reels/818171bd-dd06-4fb3-bfd2-42c5040a3381.jpg',
    mime: 'video/mp4',
    size_bytes: 8140000,
    duration_sec: 14,
    width: 1080,
    height: 1920,
    targets: ['ig_reel'],
    caption: 'Ham şantiye sahası videosu — Montaj Stüdyosunda fon müziği ve kanca sorusu eklenerek Reels yapılabilir.',
    hashtags: ['#şantiye', '#hamvideo', '#embayyapı'],
    edit: { trim_start: 0, trim_end: 14, muted: false },
    notes: 'Ham kamera çekimi',
    status: 'pool' as const,
    draft_ids: [],
    queued_at: null,
    created_at: new Date(Date.now() - 86400_000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-vid-6',
    kind: 'video' as const,
    source: 'upload' as const,
    is_edited: false,
    title: 'Ham Çekim: Manitou Çatal ile Palet İndirme & İstif',
    url: '/reels/96e5c7bd-0a92-47a7-9867-057cf4fa7fdc.mp4',
    original_url: '/reels/96e5c7bd-0a92-47a7-9867-057cf4fa7fdc.mp4',
    cover_url: '/reels/96e5c7bd-0a92-47a7-9867-057cf4fa7fdc.jpg',
    mime: 'video/mp4',
    size_bytes: 5650000,
    duration_sec: 10,
    width: 1080,
    height: 1920,
    targets: ['ig_reel'],
    caption: 'Şantiye kamyonundan paletli malzeme tahliyesi. Manitou ile hızlı ve güvenli indirme.',
    hashtags: ['#manitou', '#malzemeistif', '#şahinmanitou'],
    edit: { trim_start: 0, trim_end: 10, muted: false },
    notes: 'Ham makine çekimi',
    status: 'pool' as const,
    draft_ids: [],
    queued_at: null,
    created_at: new Date(Date.now() - 86400_000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_AUDIO_TRACKS = [
  { id: 'track-reels', name: 'Şantiye & Endüstriyel Dinamik Bas', src: '/audio/music.m4a', duration: '0:32', mood: 'Dinamik / Şantiye' },
  { id: 'track-urban', name: 'Modern Kentsel Dönüşüm Beat', src: '/audio/music.m4a', duration: '0:28', mood: 'Kurumsal / İlham Verici' },
  { id: 'track-tempo', name: 'Hızlı İlerleme & Reels Ritim', src: '/audio/music.m4a', duration: '0:25', mood: 'Hızlı / Enerjik' },
];

export const DEMO_REALISTIC_DRAFTS = [
  {
    id: 'demo-draft-1',
    title: 'Genel İnşaat Reels: 150 Günde Temelden Çatıya Villa İnşaatı',
    body: 'Çatalca ve Silivri hattında müstakil villa projelerimiz hızla yükseliyor. Temelden anahtar teslime kadar statik ve mimari taahhüt. ☎ 0531 436 29 04',
    caption: 'Çatalca ve Silivri hattında müstakil villa projelerimiz hızla yükseliyor. Temelden anahtar teslime kadar statik ve mimari taahhüt. Detaylı keşif için bize ulaşın: 0531 436 29 04',
    headline: '150 GÜNDE ANAHTAR TESLİM VİLLA',
    hashtags: ['#inşaat', '#villayapımı', '#çatalca', '#müteahhitlik', '#embayyapı'],
    cta: 'Hemen Keşif İsteyin',
    primary_platform: 'instagram',
    platform_targets: ['instagram', 'youtube'],
    networks: ['instagram', 'youtube'],
    format: 'instagram_reel',
    status: 'onay_bekliyor',
    workflow_status: 'pending_approval',
    scheduled_at: new Date(Date.now() + 3600_000 * 2).toISOString(),
    media_urls: ['/brand/video/embay-150-gunde-villa-kapak.jpg'],
    video_url: '/brand/video/embay-150-gunde-villa.mp4',
    brand: 'Embay Yapı',
    created_at: new Date().toISOString(),
    approval_request_id: 'appr-1',
  },
  {
    id: 'demo-draft-2',
    title: 'Manitou Kiralama: 18m Operatörlü Teleskopik Yükleyici',
    body: 'Güngören, Hadımköy, Çorlu ve İkitelli şantiyelerinde aynı gün teslim operatörlü Manitou MT-X 1840. Malzeme paleti ve cam montajı sepeti dahil.',
    caption: 'İstanbul geneli şantiyelerinize aynı gün sevk! 18 Metre erişim, 4 ton kaldırma kapasitesi, sertifikalı operatör güvencesi. Teklif hattı: 0531 436 29 04',
    headline: 'OPERATÖRLÜ MANİTOU KİRALAMA',
    hashtags: ['#manitoukiralama', '#şahinmanitou', '#inşaatmakinesi', '#şantiye'],
    cta: 'Teklif Al: 0531 436 29 04',
    primary_platform: 'instagram',
    platform_targets: ['instagram', 'facebook'],
    networks: ['instagram', 'facebook'],
    format: 'instagram_post',
    status: 'zamanlandi',
    workflow_status: 'scheduled',
    scheduled_at: new Date(Date.now() + 3600_000 * 6).toISOString(),
    media_urls: ['/reels/82d879bd-1f6c-4cb4-844f-8667ac972bfb.jpg'],
    video_url: null,
    brand: 'Şahin Manitou',
    created_at: new Date().toISOString(),
    approval_request_id: 'appr-2',
  },
  {
    id: 'demo-draft-3',
    title: 'Kentsel Dönüşüm Gönderisi: Depreme Dayanıklı Temel İmalatı',
    body: 'Güngören Tozkoparan’da yerinde dönüşüm projelerimizde radye temel ve C35 hazır beton kalitesiyle geleceğinizi güvenceye alıyoruz.',
    caption: 'Güngören Tozkoparan’da yerinde dönüşüm projelerimizde radye temel ve C35 hazır beton kalitesiyle geleceğinizi güvenceye alıyoruz. Bina analizi ve kat malikleri toplantısı için arayabilirsiniz.',
    headline: 'GÜNGÖREN KENTSEL DÖNÜŞÜM',
    hashtags: ['#kentseldönüşüm', '#güngören', '#depremyönetmeliği', '#embayyapı'],
    cta: 'Ücretsiz Danışmanlık',
    primary_platform: 'linkedin',
    platform_targets: ['linkedin', 'facebook'],
    networks: ['linkedin', 'facebook'],
    format: 'linkedin_post',
    status: 'onaylandi',
    workflow_status: 'approved',
    scheduled_at: new Date(Date.now() + 86400_000).toISOString(),
    media_urls: ['/brand/embay-kapak.jpg'],
    video_url: null,
    brand: 'Embay Yapı',
    created_at: new Date().toISOString(),
    approval_request_id: 'appr-3',
  },
  {
    id: 'demo-draft-4',
    title: 'Şantiye Hikayesi: Kolon Demiri Bağlama & Statik Kontrol',
    body: 'Şantiyede bugünün mesaisi: 4. kat döşeme ve perde demirleri bağlandı, yapı denetim onayı tamam. Yarın sabah 07:00 beton dökümü.',
    caption: 'Perde ve kolon donatı imalatı tamamlandı. Embay Yapı kalitesi her aşamada şeffaf.',
    headline: 'ŞANTİYEDE BUGÜN',
    hashtags: ['#şantiye', '#embayyapı', '#hikaye'],
    cta: '0531 436 29 04',
    primary_platform: 'instagram',
    platform_targets: ['instagram'],
    networks: ['instagram'],
    format: 'instagram_story',
    status: 'taslak',
    workflow_status: 'draft',
    scheduled_at: new Date(Date.now() + 86400_000 * 2).toISOString(),
    media_urls: ['/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.jpg'],
    video_url: null,
    brand: 'Embay Yapı',
    created_at: new Date().toISOString(),
    approval_request_id: null,
  },
];

export const DEMO_ENGAGEMENT_LEADS = [
  {
    id: 'eng-1',
    author: 'Karadeniz İnşaat Taahhüt',
    handle: 'karadeniz_yapi_ist',
    platform: 'instagram',
    url: 'https://www.instagram.com/p/C7X123456/',
    summary: 'Hadımköy Sanayi Sitesi 2. Kısım için götürü kaba inşaat kalıp demir taşeronu aranıyor (3 katlı fabrika yapısı).',
    suggested_comment: 'Merhaba, Hadımköy sanayi şantiyelerine kendi kalıp-demir ekiplerimiz ve Manitou yükleyicilerimizle anahtar teslim taahhüt veriyoruz. Detayları görüşmek isteriz ☎ 0531 436 29 04',
    category: 'Götürü Kaba İnşaat / Taşeron Arayışı',
    phone: '0532 410 XX XX',
    likes: 42,
    comments: 8,
    is_liked: false,
    is_commented: false,
  },
  {
    id: 'eng-2',
    author: 'Avrupa Prefabrik & Çelik',
    handle: 'avrupa_celik_yapi',
    platform: 'instagram',
    url: 'https://www.instagram.com/p/C8Y987654/',
    summary: 'Çorlu Çerkezköy organize sanayi bölgesinde çelik çatı ve panel montajı için 18 metre sepetli Manitou telehandler aranıyor.',
    suggested_comment: 'Merhaba, Şahin Manitou olarak 18m MT-X 1840 makinelerimiz ve uzman operatörlerimizle Çorlu ve Çerkezköy şantiyelerine günlük/haftalık sevk yapıyoruz. ☎ 0531 436 29 04',
    category: 'Manitou / Telehandler Arayışı',
    phone: '0533 620 XX XX',
    likes: 85,
    comments: 14,
    is_liked: false,
    is_commented: false,
  },
  {
    id: 'eng-3',
    author: 'Tozkoparan Konut Sakinleri Platformu',
    handle: 'tozkoparan_donusum',
    platform: 'instagram',
    url: 'https://www.instagram.com/p/C9Z112233/',
    summary: 'Güngören Tozkoparan’da 18 daireli binamız için kentsel dönüşüm müteahhidi arıyoruz. Güvenilir ve yerel firma teklifleri bekleniyor.',
    suggested_comment: 'Embay Yapı olarak Güngören Tozkoparan merkezli çalışıyor, deprem yönetmeliğine uygun projelendirme ve garantili teslim yapıyoruz. Ücretsiz ön keşif için Samet Bey ile görüşebilirsiniz: 0531 436 29 04',
    category: 'Kentsel Dönüşüm / Müteahhitlik Talebi',
    phone: '0530 115 XX XX',
    likes: 129,
    comments: 31,
    is_liked: false,
    is_commented: false,
  },
];

export const DEMO_REALISTIC_BANNERS = [
  {
    id: 'demo-banner-1',
    kind: 'banner' as const,
    title: '150 Günde Anahtar Teslim Villa Taahhüdü',
    url: '/brand/embay-kapak.jpg',
    width: 1080,
    height: 1350,
    platform: 'instagram',
    pillar: 'villa',
    source: 'factory',
    caption: 'Silivri, Çatalca ve Tekirdağ hattında kendi arsasına müstakil villa yaptırmak isteyenlere 150 günde anahtar teslim teslim taahhüt. C35 beton, radye temel, mimari ve statik projelendirme. Bilgi: 0531 436 29 04',
    hashtags: ['#embayyapı', '#villayapımı', '#çatalca', '#müteahhitlik', '#anahtarteslim'],
    use_count: 5,
    status: 'active',
    created_at: new Date(Date.now() - 3600_000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
    template: {
      brand: 'Embay Yapı',
      badge: 'VİLLA PROJESİ',
      headline: '150 GÜNDE ANAHTAR TESLİM VİLLA',
      subtitle: 'Arsanıza özel depreme dayanıklı betonarme ve modern villa imalatı.',
      cta: '0531 436 29 04',
      photo_url: '/brand/embay-kapak.jpg',
    },
  },
  {
    id: 'demo-banner-2',
    kind: 'banner' as const,
    title: 'Şahin Manitou: 18m Operatörlü Telehandler Kiralama',
    url: '/reels/82d879bd-1f6c-4cb4-844f-8667ac972bfb.jpg',
    width: 1080,
    height: 1350,
    platform: 'instagram',
    pillar: 'manitou',
    source: 'factory',
    caption: 'İstanbul Avrupa ve Anadolu yakası şantiyeleri için günlük, haftalık ve aylık kiralık operatörlü Manitou teleskopik yükleyiciler. Palet, çatal ve insan sepeti ataşmanlı. ☎ 0531 436 29 04',
    hashtags: ['#şahinmanitou', '#manitoukiralama', '#teleskopikyükleyici', '#şantiyelojistik'],
    use_count: 8,
    status: 'active',
    created_at: new Date(Date.now() - 3600_000 * 18).toISOString(),
    updated_at: new Date().toISOString(),
    template: {
      brand: 'Şahin Manitou',
      badge: 'KİRALIK İŞ MAKİNESİ',
      headline: 'OPERATÖRLÜ 18M MANİTOU KİRALAMA',
      subtitle: 'Şantiyenize aynı gün sevk, uzman operatör ve tam donanımlı ataşmanlar.',
      cta: 'Hemen Teklif Al: 0531 436 29 04',
      photo_url: '/reels/82d879bd-1f6c-4cb4-844f-8667ac972bfb.jpg',
    },
  },
  {
    id: 'demo-banner-3',
    kind: 'banner' as const,
    title: 'Güngören Tozkoparan Kentsel Dönüşüm & Bina Güçlendirme',
    url: '/brand/embay-profil.jpg',
    width: 1080,
    height: 1350,
    platform: 'facebook',
    pillar: 'donusum',
    source: 'factory',
    caption: 'Güngören Tozkoparan merkezli Embay Yapı ile yerinde kentsel dönüşüm. Kat malikleriyle şeffaf sözleşme, hızlı ruhsat ve anahtar teslim inşaat güvencesi. ☎ 0531 436 29 04',
    hashtags: ['#kentseldönüşüm', '#güngören', '#tozkoparan', '#depremgüvenliği', '#embayyapı'],
    use_count: 4,
    status: 'active',
    created_at: new Date(Date.now() - 86400_000).toISOString(),
    updated_at: new Date().toISOString(),
    template: {
      brand: 'Embay Yapı',
      badge: 'KENTSEL DÖNÜŞÜM',
      headline: 'GÜVENLİ VE YERİNDE DÖNÜŞÜM',
      subtitle: 'Tozkoparan ve Güngören için deprem yönetmeliğine tam uyumlu konut projeleri.',
      cta: 'Ücretsiz Bina Analizi',
      photo_url: '/brand/embay-profil.jpg',
    },
  },
  {
    id: 'demo-banner-4',
    kind: 'banner' as const,
    title: 'Kaba İnşaat, Kalıp & Donatı Demir İmalatı',
    url: '/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.jpg',
    width: 1080,
    height: 1350,
    platform: 'instagram',
    pillar: 'santiye',
    source: 'factory',
    caption: 'Müteahhitlik ve götürü taşeronluk projelerinizde kendi kalıpçı, demirci ekiplerimiz ve şantiye şeflerimizle hizmetinizdeyiz. ☎ 0531 436 29 04',
    hashtags: ['#kabainşaat', '#kalıpdemir', '#müteahhit', '#şantiye', '#embayyapı'],
    use_count: 3,
    status: 'active',
    created_at: new Date(Date.now() - 86400_000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
    template: {
      brand: 'Embay Yapı',
      badge: 'KABA İNŞAAT & TAŞERON',
      headline: 'UZMAN KALIP VE DEMİR EKİPLERİ',
      subtitle: 'Projeye ve statik hesaplara milimetrik uygun kaba inşaat taahhüdü.',
      cta: '0531 436 29 04',
      photo_url: '/reels/7e80a3ff-ef45-4e4d-925c-c8f8c78222a7.jpg',
    },
  },
];

export const DEMO_REALISTIC_POST_TEMPLATES = [
  {
    id: 'demo-post-tpl-1',
    title: 'Genel İnşaat: Götürü Kalıp, Demir & Kaba İnşaat Taahhüdü',
    platform: 'instagram',
    brand: 'Embay Yapı',
    pillar: 'Genel İnşaat',
    headline: 'GÖTÜRÜ KABA İNŞAAT VE MÜTEAHHİTLİK HİZMETİ',
    caption: 'İstanbul Avrupa ve Anadolu yakasında devam eden projeleriniz için profesyonel taşeronluk ve müteahhitlik taahhüdü. Kendi usta kalıpçı ve demirci ekiplerimiz, kalıp malzememiz ve Manitou iş makinelerimizle şantiyenizde hız ve kaliteyi bir arada sunuyoruz. İster götürü ister birim fiyatlı kaba inşaat teklifi almak için bizimle iletişime geçebilirsiniz.',
    hashtags: ['#embayyapı', '#kabainşaat', '#kalıpdemir', '#müteahhitlik', '#taşeron', '#şantiye'],
    cta: '0531 436 29 04',
    notes: 'Kaba inşaat ve götürü işler için hazır paylaşım metni',
    source: 'factory',
    use_count: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-post-tpl-2',
    title: 'Şahin Manitou: 14m ve 18m Operatörlü Teleskopik Yükleyici',
    platform: 'instagram',
    brand: 'Şahin Manitou',
    pillar: 'Manitou Kiralama',
    headline: 'ŞANTİYENİZE AYNI GÜN SEVK EDİLEN MANİTOU FİLOSU',
    caption: 'Şantiyenizde katlara paletli tuğla ve harç çıkarma, çelik konstrüksiyon montajı, dış cephe cam takma veya insan sepetiyle yüksekte çalışma işleri mi var? Şahin Manitou MT-X 1840 makinelerimiz ve tecrübeli operatörlerimizle 7/24 hizmetinizde. Günlük, haftalık ve aylık uygun kiralama koşulları için hemen arayın.',
    hashtags: ['#şahinmanitou', '#manitoukiralama', '#teleskopikyükleyici', '#vinçkiralama', '#şantiyelojistik'],
    cta: 'Hemen Arayın: 0531 436 29 04',
    notes: 'Manitou kiralama müşterileri için ana tanıtım şablonu',
    source: 'factory',
    use_count: 19,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-post-tpl-3',
    title: 'Kentsel Dönüşüm: Güngören & Tozkoparan Yerinde Dönüşüm',
    platform: 'facebook',
    brand: 'Embay Yapı',
    pillar: 'Kentsel Dönüşüm',
    headline: 'BİNANIZI GÜVENLE YENİLEYİN — EMBAY YAPI GÜVENCESİ',
    caption: 'Deprem riskine karşı eski binalarınızı modernize ediyoruz. Güngören Tozkoparan merkezli yerel tecrübemiz ile kat malikleri toplantılarından belediye ruhsat aşamasına ve anahtar teslimine kadar tüm süreci şeffaf yönetiyoruz. Ücretsiz yerinde keşif ve statik bina değerlendirmesi için bizimle görüşün.',
    hashtags: ['#kentseldönüşüm', '#güngören', '#tozkoparan', '#depremgüvenliği', '#yerindedönüşüm'],
    cta: 'Ücretsiz Danışmanlık: 0531 436 29 04',
    notes: 'Kentsel dönüşüm talebi toplayan güven şablonu',
    source: 'factory',
    use_count: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-post-tpl-4',
    title: '150 Günde Villa İnşaatı Şantiye İlerleme Günlüğü',
    platform: 'instagram',
    brand: 'Embay Yapı',
    pillar: 'Villa Projeleri',
    headline: '150 GÜNDE TEMELDEN ÇATIYA ANAHTAR TESLİM VİLLA',
    caption: 'Arsanız hazırsa hayalinizdeki villayı 150 günde teslim ediyoruz. Radye temel, su ve ısı izolasyonu, 1. sınıf betonarme taşıyıcı sistem ve lüks iç mimari detaylar. Çatalca, Silivri ve Tekirdağ projelerimizi yerinde incelemek için randevu alabilirsiniz.',
    hashtags: ['#villainşaatı', '#çatalca', '#silivri', '#anahtarteslimvilla', '#embayyapı'],
    cta: '0531 436 29 04',
    notes: 'Müstakil ev ve villa yaptıranlara yönelik şablon',
    source: 'factory',
    use_count: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

