import assert from 'node:assert/strict';
import { parseFindingDate, publicationDateIssue, recencyWindow } from '../supabase/functions/_shared/recency.ts';
import { findingDateIssue, makePublicationEvidence, publicationFromHtml, sourceSupportsTitle, trustedPublication } from '../supabase/functions/_shared/pure/publication.ts';

let checks = 0;
const equal = (actual: unknown, expected: unknown) => { assert.deepEqual(actual, expected); checks++; };
const truth = (actual: unknown) => { assert.ok(actual); checks++; };
const now = new Date('2026-10-09T01:00:00+03:00');
const recent = { goal: 'Son 30 gün içindeki gerçek müşteri talepleri' };
const url = 'https://example.com/talep';
for (const invalid of ['2 saat önce', 'bugün', '2026', 'Ekim 2026', '31.02.2026', '2026-02-29', '2026-13-01', 'yeni: 2026-10-08', '2026-00-05']) equal(parseFindingDate(invalid), null);
for (const valid of ['2026-10-08', '2026-10-08T11:12:13Z', '8.10.2026', '8/10/2026', '8 Ekim 2026', '8 Eki 2026', '29 Şubat 2024']) truth(parseFindingDate(valid));
equal(recencyWindow(recent, now), { required: true, from: '2026-09-09', to: '2026-10-09', days: 30 });
equal(recencyWindow({ goal: 'Son 7 gün' }, now).from, '2026-10-02');
equal(recencyWindow({ goal: 'Son iki hafta' }, now).days, 14);
equal(recencyWindow({ goal: 'Son 1 ay' }, now).days, 30);
equal(recencyWindow({ goal: 'Bu hafta' }, now).from, '2026-10-05');
equal(recencyWindow({ goal: 'Bu ay' }, now).from, '2026-10-01');
equal(recencyWindow({ goal: 'Bugün' }, now).from, '2026-10-09');
equal(publicationDateIssue('2026-09-09', recent, now), null);
truth(publicationDateIssue('2026-09-08', recent, now));
truth(publicationDateIssue('2018-08-27', recent, now));
truth(publicationDateIssue('2026-10-10', recent, now));
equal(publicationDateIssue('2026-10-09', recent, now), null); // bugün, ileri saat bilgisi yok
truth(publicationDateIssue(undefined, recent, now));
equal(publicationDateIssue(undefined, { goal: 'Mimarlık ofisi profilleri' }, now), null);
const source = makePublicationEvidence('2026-10-08', 'search_metadata', url)!;
equal(source.posted, '2026-10-08');
equal(findingDateIssue(source, url, recent, now), null);
equal(trustedPublication(source, url + '#fragment')?.posted, '2026-10-08');
equal(trustedPublication(source, 'https://example.com/baska-talep'), undefined);
truth(findingDateIssue(source, 'https://example.com/baska-talep', recent, now));
truth(findingDateIssue(undefined, url, recent, now)); // AI posted iddiasına parametre dahi yok
equal(makePublicationEvidence('2 saat önce', 'search_metadata', url), undefined);
equal(makePublicationEvidence('2026-10-08', 'search_metadata', 'javascript:alert(1)'), undefined);
equal(publicationFromHtml('<meta content="2026-10-08T11:12:13+03:00" property="article:published_time">', url)?.posted, '2026-10-08');
equal(publicationFromHtml("<meta itemprop='datePublished' content='2026-10-08'>", url)?.origin, 'page_metadata');
equal(publicationFromHtml('<meta property="article:modified_time" content="2026-10-08">', url), undefined);
equal(publicationFromHtml('<meta name="date" content="2026-10-08">', url), undefined);
const ld = (o: unknown) => `<script type="application/ld+json">${JSON.stringify(o)}</script>`;
equal(publicationFromHtml(ld({ '@type': 'Article', url, datePublished: '2018-08-27', dateModified: '2026-10-08' }), url)?.posted, '2018-08-27');
equal(publicationFromHtml(ld({ '@type': 'Article', url, dateModified: '2026-10-08' }), url), undefined);
equal(publicationFromHtml(ld({ '@type': 'Article', url: 'https://example.com/ilgili-yazi', datePublished: '2026-10-08' }), url), undefined);
equal(publicationFromHtml(ld({ '@type': 'Comment', datePublished: '2026-10-08' }), url), undefined);
equal(publicationFromHtml(ld({ '@type': 'Article', url, comment: { datePublished: '2026-10-08' } }), url), undefined);
equal(publicationFromHtml(ld({ '@graph': [{ '@type': 'Article', url, datePublished: '2026-10-08' }, { '@type': 'Article', url: 'https://example.com/yan', datePublished: '2026-10-09' }] }), url)?.posted, '2026-10-08');
equal(publicationFromHtml(ld([{ '@type': 'Article', datePublished: '2026-10-08' }, { '@type': 'Article', datePublished: '2026-10-09' }]), url), undefined);
equal(publicationFromHtml('<script type="application/ld+json">{broken}</script>', url), undefined);
equal(parseFindingDate('2026-10-08T26:00:00Z'), null);
equal(recencyWindow({ goal: 'son30gün' }, now).days, 30);
equal(recencyWindow({ goal: 'son30gün' }, now).required, true);
equal(sourceSupportsTitle('EV', 'Giriş yapın'), false);
equal(sourceSupportsTitle('Çatalca çelik ev müşteri talebi', 'Lütfen hesabınıza giriş yapın'), false);
equal(sourceSupportsTitle('Çatalca çelik ev müşteri talebi', 'Çatalca çelik ev müşteri talebi yayımlandı'), true);
equal(sourceSupportsTitle('Çatalca çelik ev müşteri talebi', 'Ankara yazılım pazar büyüklüğü'), false);
equal(sourceSupportsTitle('Çatalca çelik ev müşteri talebi', ''), false);
console.log(`publication contract: ${checks} assertions passed`);
