import { useEffect, useState } from 'react';
import { BarChart3, Save, Target } from 'lucide-react';
import { supabase } from '../lib/supabase';

type MetricDraft = { id: string; title: string; platform_targets: string[]; impressions: number | null; engagements: number | null; leads_count: number | null; conversions_count: number | null; ad_strategy: string | null; performance_notes: string | null };

export function SocialMetricsPanel() {
  const [items, setItems] = useState<MetricDraft[]>([]);
  const [selectedId, setSelectedId] = useState('');
  const [form, setForm] = useState({ impressions: '', engagements: '', leads: '', conversions: '', strategy: '', notes: '' });
  const [message, setMessage] = useState('');
  useEffect(() => { const load = async () => { if (!supabase) return; const { data } = await supabase.from('social_drafts').select('id,title,platform_targets,impressions,engagements,leads_count,conversions_count,ad_strategy,performance_notes').order('scheduled_at', { ascending: false }).limit(100); setItems((data || []) as MetricDraft[]); }; load(); }, []);
  const selected = items.find(item => item.id === selectedId);
  const selectItem = (id: string) => { const item = items.find(entry => entry.id === id); setSelectedId(id); setForm({ impressions: item?.impressions?.toString() || '', engagements: item?.engagements?.toString() || '', leads: item?.leads_count?.toString() || '', conversions: item?.conversions_count?.toString() || '', strategy: item?.ad_strategy || '', notes: item?.performance_notes || '' }); setMessage(''); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!supabase || !selectedId) return; const result = await supabase.from('social_drafts').update({ impressions: Number(form.impressions) || 0, engagements: Number(form.engagements) || 0, leads_count: Number(form.leads) || 0, conversions_count: Number(form.conversions) || 0, ad_strategy: form.strategy || null, performance_notes: form.notes || null }).eq('id', selectedId); if (result.error) setMessage('Metrikler kaydedilemedi.'); else { setItems(current => current.map(item => item.id === selectedId ? { ...item, impressions: Number(form.impressions) || 0, engagements: Number(form.engagements) || 0, leads_count: Number(form.leads) || 0, conversions_count: Number(form.conversions) || 0, ad_strategy: form.strategy, performance_notes: form.notes } : item)); setMessage('Performans kaydı güncellendi.'); } };
  return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-2 mb-1"><BarChart3 className="w-5 h-5 text-cyan-300" /><h3 className="text-lg font-black text-white">Performans, dönüşüm ve reklam stratejisi</h3></div><p className="text-xs text-slate-400 mb-4">Yayın sonrası gerçek platform verilerini girin; sonraki reklam ve içerik kararları arşiv kaydına bağlansın.</p>{items.length === 0 ? <div className="rounded-xl border border-dashed border-slate-700 p-6 text-center text-sm text-slate-400">Metrik girişi için önce bir gönderi planlayın.</div> : <form onSubmit={save} className="space-y-4"><select value={selectedId} onChange={e => selectItem(e.target.value)} className="w-full px-3 py-2.5 rounded-lg bg-slate-950 border border-slate-700 text-white text-sm"><option value="">Gönderi seçin</option>{items.map(item => <option key={item.id} value={item.id}>{item.title} · {(item.platform_targets || []).join(', ')}</option>)}</select>{selected && <><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[['impressions', 'Gösterim'], ['engagements', 'Etkileşim'], ['leads', 'Lead'], ['conversions', 'Dönüşüm']].map(([key, label]) => <label key={key} className="text-xs text-slate-400">{label}<input type="number" min="0" value={form[key as keyof typeof form]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full px-3 py-2 rounded-lg bg-slate-950 border border-slate-700 text-white" /></label>)}</div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><textarea value={form.strategy} onChange={e => setForm({ ...form, strategy: e.target.value })} placeholder="Geri dönüşe göre reklam stratejisi" rows={3} className="px-3 py-2 rounded-lg bg-slate-950 border border-slate-700 text-white text-sm" /><textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} placeholder="Sonuç / sonraki öneri / rapor notu" rows={3} className="px-3 py-2 rounded-lg bg-slate-950 border border-slate-700 text-white text-sm" /></div><div className="flex items-center justify-between"><span className="text-xs text-emerald-300 inline-flex items-center gap-1"><Target className="w-3.5 h-3.5" /> Veriler Supabase arşivine yazılır</span><button className="px-4 py-2 rounded-lg bg-cyan-600 text-white text-xs font-bold inline-flex items-center gap-2"><Save className="w-4 h-4" /> Kaydet</button></div></>}{message && <p className="text-xs text-emerald-300">{message}</p>}</form>}</section>;
}
